* Updated README and run scripts

diff --git a/scripts/run/run_restart b/scripts/run/run_restart
--- a/scripts/run/run_restart
+++ b/scripts/run/run_restart
@@ -28,7 +28,6 @@ export zaxvarname="h"
 # Model domain
 export nx=1557
 export ny=890
-export nlevels=60
 export has_subdomains=True
 export zax_style=2
 
@@ -80,8 +79,8 @@ RUN_DIR=${PWD}
 BASE_DIR=${RUN_DIR}/..
 NML_PATH=${BASE_DIR}/nml
 #--------------------
-MODEL_DIR=${BASE_DIR}/bin
-MODEL_BIN=${MODEL_DIR}/main
+MODEL_DIR=${BASE_DIR}/build # ! May need to change this
+MODEL_BIN=${MODEL_DIR}/ParticleModel # ! May need to change this
 #--------------------
 OUT_BASE_DIR="${RUN_DIR}/out"
 #--------------------
@@ -156,7 +155,14 @@ while [ $(date -d "$dateval" +%s) -lt $(date -d "$date_end" +%s) ]; do
     echo "Running model..."
     tic_m=$(date +%s)
     ${MODEL_BIN}
+    err=$?
     toc_m=$(date +%s)
+    if [ $err -ne 0 ]; then
+        echo "Model exited with error"
+        exit
+    else 
+        echo "Model exited without errors"
+    fi
     #--------------------
     echo "Model run number ${num_run} finished"
     echo "Model wall time: $((toc_m-tic_m)) seconds" 
