* Updated test cases

diff --git a/test_cases/Tagus_3d/run b/test_cases/Tagus_3d/run
--- a/test_cases/Tagus_3d/run
+++ b/test_cases/Tagus_3d/run
@@ -29,7 +29,6 @@ export zaxvarname="depth"
 # Model domain
 export nx=145
 export ny=120
-export nlevels=50
 export has_subdomains=False
 export zax_style=0
 export zax_direction=-1
@@ -37,7 +36,7 @@ export zax_direction=-1
 # Parameters
 export sw_rho_default=1035.
 
-# Advetion + buoyancy
+# Advection + buoyancy
 export do_velocity=True
 
 # Diffusion
@@ -50,8 +49,8 @@ export resuspension_threshold=0.0048
 
 # Biofouling
 export do_biofouling=False
-gt=10 # growth time in days
-export growth_timescale=`python3 -c "print($gt*24.*3600.)"` # in seconds
+gt=10                                                        # growth time in days
+export growth_timescale=$(python3 -c "print($gt*24.*3600.)") # in seconds
 
 # Boundary interactions
 export kill_beached=True
@@ -65,14 +64,20 @@ export dt=30.
 export particle_init_method=1
 export coordfile="${PWD}/data/input/init_particles_full.dat"
 in_hours=99999
-export inputstep=`python3 -c "print(int($in_hours*3600./$dt))"`
+export inputstep=$(python3 -c "print(int($in_hours*3600./$dt))")
 
 # Output
 out_hours=0.5
-export outputstep=`python3 -c "print(int($out_hours*3600./$dt))"`
+export outputstep=$(python3 -c "print(int($out_hours*3600./$dt))")
 export write_all_particles=True
 export write_active_particles=False
 export write_snapshot=False
+
+# Postprocess
+export enable_postprocessing=False # <-- Change to True for postprocessing
+export postprocessor_output_frequency=10
+export postprocessor_grid_size=250.
+export postprocessor_nlevels=4
 
 # Restart
 # Restart variable is set below
@@ -86,8 +91,8 @@ RUN_DIR=${PWD}
 BASE_DIR=${RUN_DIR}/../..
 NML_PATH=${BASE_DIR}/nml
 #--------------------
-MODEL_DIR=${BASE_DIR}/bin
-MODEL_BIN=${MODEL_DIR}/main
+MODEL_DIR=${BASE_DIR}/build # <-- 
+MODEL_BIN=${MODEL_DIR}/ParticleModel # <--
 #--------------------
 OUT_BASE_DIR="${RUN_DIR}/out"
 #--------------------
@@ -114,7 +119,7 @@ tic=$(date +%s)
 #--------------------
 while [ $(date -d "$dateval" +%s) -lt $(date -d "$date_end" +%s) ]; do
     #--------------------
-    num_run=$((num_run+1))
+    num_run=$((num_run + 1))
     echo "===================="
     echo "This is run number $num_run"
     echo "Date: $dateval"
@@ -153,7 +158,14 @@ while [ $(date -d "$dateval" +%s) -lt $(date -d "$date_end" +%s) ]; do
     outdir_prev=$outdir
     #--------------------
     # Make namelists
-    ${NML_PATH}/makenamelist.py -i ${NML_PATH}/nmltemplate
+    python3 ${NML_PATH}/makenamelist.py -i ${NML_PATH}/nmltemplate
+    err=$?
+    if [ $err -ne 0 ]; then
+        echo "===================="
+        echo "ERROR: Failed to make namelist"
+        echo "===================="
+        exit 1
+    fi
     cp input.inp ${outdir}/.
     #--------------------
     # Run model
@@ -165,12 +177,12 @@ while [ $(date -d "$dateval" +%s) -lt $(date -d "$date_end" +%s) ]; do
     if [ $err -ne 0 ]; then
         echo "Model exited with error"
         exit
-    else 
+    else
         echo "Model exited without errors"
     fi
     #--------------------
     echo "Model run number ${num_run} finished"
-    echo "Model wall time: $((toc_m-tic_m)) seconds" 
+    echo "Model wall time: $((toc_m - tic_m)) seconds"
     echo "===================="
     #--------------------
     # Copy output
@@ -182,7 +194,7 @@ done
 toc=$(date +%s)
 echo "===================="
 echo "All finished!"
-echo "Total time: $((toc-tic)) seconds"
+echo "Total time: $((toc - tic)) seconds"
 echo "===================="
 if [ "$dry_run" = True ]; then
     echo "Dry run finished"
@@ -193,7 +205,7 @@ fi
 #======================================================================
 clear
 mkdir -p ${OUT_BASE_DIR}/counts
-for d in $( ls -d ${OUT_BASE_DIR}/2* ); do
+for d in $(ls -d ${OUT_BASE_DIR}/2*); do
     echo "Calculating counts in $d"
     python3 calculate_counts.py -O -np 8 -s $d/${runid}.out.nc -o ${OUT_BASE_DIR}/counts/counts.$(basename $d).nc --topo-file ${topofile} -dx 500
 done
diff --git a/test_cases/gof_250m_3d/run b/test_cases/gof_250m_3d/run
--- a/test_cases/gof_250m_3d/run
+++ b/test_cases/gof_250m_3d/run
@@ -83,8 +83,8 @@ RUN_DIR=${PWD}
 BASE_DIR=${RUN_DIR}/../..
 NML_PATH=${BASE_DIR}/nml
 #--------------------
-MODEL_DIR=${BASE_DIR}/bin
-MODEL_BIN=${MODEL_DIR}/main
+MODEL_DIR=${BASE_DIR}/build
+MODEL_BIN=${MODEL_DIR}/ParticleModel
 #--------------------
 OUT_BASE_DIR="${RUN_DIR}/out"
 #--------------------
@@ -149,8 +149,22 @@ while [ $(date -d "$dateval" +%s) -lt $(date -d "$date_end" +%s) ]; do
     outdir_prev=$outdir
     #--------------------
     # Make namelists
-    ${NML_PATH}/makenamelist.py -i ${NML_PATH}/nmltemplate
-    ${NML_PATH}/makenamelist.py -i ${NML_PATH}/nmltemplate_biofouling_simple -o biofouling.inp
+    python3 ${NML_PATH}/makenamelist.py -i ${NML_PATH}/nmltemplate
+    err=$?
+    if [ $err -ne 0 ]; then
+        echo "===================="
+        echo "ERROR: Failed to make namelist"
+        echo "===================="
+        exit 1
+    fi
+    python3 ${NML_PATH}/makenamelist.py -i ${NML_PATH}/nmltemplate_biofouling_simple -o biofouling.inp
+    err=$?
+    if [ $err -ne 0 ]; then
+        echo "===================="
+        echo "ERROR: Failed to make namelist"
+        echo "===================="
+        exit 1
+    fi
     cp input.inp ${outdir}/.
     #--------------------
     # Run model
